package io.timeback.domain;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/** Dependency-free synthesis runner for the approved pure-domain scope. */
public final class DomainEngineTestRunner {
    private static int passed;
    public static void main(String[] args) {
        run("invalid interval is rejected", DomainEngineTestRunner::invalidIntervalRejected);
        run("adjacent intervals do not overlap and union once", DomainEngineTestRunner::intervalUnion);
        run("DST slicing preserves absolute duration", DomainEngineTestRunner::dstDurationPreserved);
        run("unclassified app remains unclassified with neutral fallback", DomainEngineTestRunner::unclassifiedFallback);
        run("conflicting app and activity requires confirmation", DomainEngineTestRunner::conflictRequiresConfirmation);
        run("current confirmed revision excludes superseded waste", DomainEngineTestRunner::supersededWasteExcluded);
        run("conflicting current revisions are rejected", DomainEngineTestRunner::conflictingCurrentRejected);
        run("measurement retry is idempotent and baseline needs seven consecutive days", DomainEngineTestRunner::measurementAndBaseline);
        run("partial coverage and saved rate precedence are explicit", DomainEngineTestRunner::partialSavedAndRate);
        run("goal overlap remains pending then resolves once", DomainEngineTestRunner::goalOverlap);
        run("timer completion commits or preserves snapshot atomically", DomainEngineTestRunner::timerCompletionAtomicity);
        run("direct Timeline edit commits atomically and preserves Context snapshot on failure", DomainCommandRegression::directTimelineEditAtomicity);
        run("APP-05 through APP-09 command paths", DomainCommandRegression::run);
        run("exact non-divisible baseline and remaining approved domain boundaries", AdditionalDomainRegression::run);
        System.out.println("PASS " + passed + " domain checks");
    }
    private static void invalidIntervalRejected() { expectThrows(() -> new Interval(t("2026-01-01T01:00:00Z"), t("2026-01-01T01:00:00Z"))); }
    private static void intervalUnion() { Interval first = interval("2026-01-01T10:00:00Z", "2026-01-01T11:00:00Z"); Interval adjacent = interval("2026-01-01T11:00:00Z", "2026-01-01T12:00:00Z"); check(!first.overlaps(adjacent), "boundary contact is not overlap"); check(Interval.unionDuration(List.of(first, adjacent)).equals(Duration.ofHours(2)), "union preserves actual time"); }
    private static void dstDurationPreserved() { ZoneId zone = ZoneId.of("America/New_York"); Interval value = new Interval(ZonedDateTime.of(2026, 3, 8, 0, 30, 0, 0, zone).toInstant(), ZonedDateTime.of(2026, 3, 8, 4, 30, 0, 0, zone).toInstant()); check(value.duration().equals(Duration.ofHours(3)), "spring DST uses absolute duration"); check(value.sliceByLocalDate(zone).stream().map(Interval::duration).reduce(Duration.ZERO, Duration::plus).equals(value.duration()), "local slicing preserves duration"); }
    private static void unclassifiedFallback() { AppProfile app = AppProfile.unclassified("example.app.unclassified", "Example A", t("2026-01-01T00:00:00Z")); AppSession session = new AppSession("s1", app.packageName(), interval("2026-01-01T10:00:00Z", "2026-01-01T11:00:00Z"), false); EffectiveDecision decision = new ContextEngine().analyze(List.of(session), Map.of(app.packageName(), app), List.of(), List.of()).get(0); check(app.state() == AppClassificationState.UNCLASSIFIED && decision.classification() == Classification.NEUTRAL, "fallback does not classify app"); }
    private static void conflictRequiresConfirmation() { AppProfile app = AppProfile.classified("example.app.waste", "Example B", Classification.WASTE, t("2026-01-01T00:00:00Z"), t("2026-01-01T00:01:00Z")); AppSession session = new AppSession("s1", app.packageName(), interval("2026-01-01T10:00:00Z", "2026-01-01T11:00:00Z"), false); ActivityRecord activity = new ActivityRecord("a1", ActivityType.STUDY, null, Classification.PRODUCTIVE, session.interval()); EffectiveDecision decision = new ContextEngine().analyze(List.of(session), Map.of(app.packageName(), app), List.of(activity), List.of()).get(0); check(decision.classification() == Classification.MIXED && decision.status() == DecisionStatus.CONFIRMATION_REQUIRED, "conflict needs confirmation"); }
    private static void supersededWasteExcluded() { AppProfile app = AppProfile.classified("example.app.waste", "Example C", Classification.WASTE, t("2026-01-01T00:00:00Z"), t("2026-01-01T00:01:00Z")); Interval time = interval("2026-01-01T10:00:00Z", "2026-01-01T11:00:00Z"); ContextRevision old = new ContextRevision("c1", "logical", 1, time, Classification.WASTE, DecisionStatus.USER_CONFIRMED, EffectiveState.SUPERSEDED, DecisionKind.TIMELINE_EDIT, null, null, t("2026-01-01T11:01:00Z")); ContextRevision current = ContextRevision.confirmed("c2", "logical", 2, time, Classification.PRODUCTIVE, t("2026-01-01T11:02:00Z")); List<EffectiveDecision> decisions = new ContextEngine().analyze(List.of(new AppSession("s1", app.packageName(), time, false)), Map.of(app.packageName(), app), List.of(), List.of(old, current)); check(decisions.get(0).classification() == Classification.PRODUCTIVE && new ContextEngine().wasteDuration(decisions).isZero(), "superseded waste is excluded"); }
    private static void conflictingCurrentRejected() { Interval time = interval("2026-01-01T10:00:00Z", "2026-01-01T11:00:00Z"); AppSession session = new AppSession("s1", "example.app.a", time, false); ContextRevision a = ContextRevision.confirmed("c1", "a", 1, time, Classification.WASTE, t("2026-01-01T11:00:00Z")); ContextRevision b = ContextRevision.confirmed("c2", "b", 1, time, Classification.PRODUCTIVE, t("2026-01-01T11:00:00Z")); expectStateThrows(() -> new ContextEngine().analyze(List.of(session), Map.of(), List.of(), List.of(a, b))); }
    private static void measurementAndBaseline() { MetricsEngine metrics = new MetricsEngine(); ZoneId utc = ZoneId.of("UTC"); MeasurementDay first = new MeasurementDay(new MeasurementKey("anonymous", LocalDate.of(2026, 1, 1), utc), CoverageStatus.COMPLETE, Duration.ofMinutes(100), 1, 1); MeasurementUpsert applied = metrics.upsert(Map.of(), first); check(applied.result() == MeasurementUpsertResult.APPLIED && metrics.upsert(applied.snapshot(), first).result() == MeasurementUpsertResult.NO_OP, "measurement retry is idempotent"); List<MeasurementDay> days = new ArrayList<>(); for (int i = 0; i < 7; i++) days.add(new MeasurementDay(new MeasurementKey("anonymous", LocalDate.of(2026, 1, 1).plusDays(i), utc), CoverageStatus.COMPLETE, Duration.ofMinutes(100), 1, 1)); Baseline baseline = metrics.firstCompleteBaseline(days).orElseThrow(); check(baseline.weeklyWaste().equals(Duration.ofMinutes(700)) && baseline.dailyAverageNanoseconds().equals(new Ratio(java.math.BigInteger.valueOf(Duration.ofMinutes(700).toNanos()), java.math.BigInteger.valueOf(7))), "seven complete days define an exact baseline"); }
    private static void partialSavedAndRate() { MetricsEngine engine = new MetricsEngine(); Baseline baseline = new Baseline(LocalDate.of(2026, 1, 1), LocalDate.of(2026, 1, 7), Duration.ofMinutes(700)); SavedMetrics saved = engine.saved(baseline, Duration.ofMinutes(130), BigDecimal.ONE, false); check(saved.savedDuration().numerator().signum() == 0 && saved.wasteDelta().numerator().equals(java.math.BigInteger.valueOf(-210).multiply(java.math.BigInteger.valueOf(Duration.ofMinutes(1).toNanos()))) && saved.wasteDelta().denominator().equals(java.math.BigInteger.valueOf(7)), "saved clamps with signed exact delta"); PartialSavedMetrics partial = engine.partialSaved(baseline, Duration.ofMinutes(30), new BigDecimal("0.5"), interval("2026-01-08T00:00:00Z", "2026-01-08T12:00:00Z"), t("2026-01-08T12:00:00Z"), false); check(partial.periodStatus() == PeriodStatus.IN_PROGRESS && partial.comparisonBasis() == ComparisonBasis.PARTIAL_COVERAGE, "continuous current coverage is partial in-progress"); RecoveryMetrics incomplete = engine.recoveryRate(engine.saved(baseline, Duration.ZERO, BigDecimal.ONE, true), Duration.ofMinutes(30), Duration.ofMinutes(10)); check(incomplete.unavailableReason() == RateUnavailableReason.DATA_INCOMPLETE && incomplete.decisionState() == RecoveryDecisionState.DECISION_REQUIRED, "data reason precedes pending decision"); SavedMetrics positive = engine.saved(baseline, Duration.ofMinutes(40), BigDecimal.ONE, false); Ratio ratio = engine.recoveryRate(positive, Duration.ofMinutes(20), Duration.ZERO).ratio(); check(ratio.numerator().equals(java.math.BigInteger.valueOf(Duration.ofMinutes(20).toNanos())) && ratio.denominator().equals(java.math.BigInteger.valueOf(Duration.ofMinutes(60).toNanos())), "ratio preserves exact components"); }
    private static void goalOverlap() { RecoveryEngine engine = new RecoveryEngine(); Goal a = new Goal("gA", "Example Goal A", Duration.ofHours(1), t("2026-01-01T00:00:00Z")); Goal b = new Goal("gB", "Example Goal B", Duration.ofHours(1), t("2026-01-01T00:00:00Z")); RecoveredTime rA = new RecoveredTime("rA", a.id(), RecoveryMethod.MANUAL, interval("2026-01-01T10:00:00Z", "2026-01-01T11:00:00Z"), t("2026-01-01T11:00:00Z")); RecoveredTime rB = new RecoveredTime("rB", b.id(), RecoveryMethod.MANUAL, interval("2026-01-01T10:30:00Z", "2026-01-01T11:30:00Z"), t("2026-01-01T11:30:00Z")); check(engine.pendingRecovered(engine.segments(List.of(rA, rB), List.of()), null).equals(Duration.ofMinutes(30)), "overlap is pending"); OverlapResolution resolution = new OverlapResolution(Set.of("rA", "rB"), interval("2026-01-01T10:30:00Z", "2026-01-01T11:00:00Z"), a.id(), 1); List<RecoverySegment> resolved = engine.segments(List.of(rA, rB), List.of(resolution)); check(engine.pendingRecovered(resolved, null).isZero() && engine.lifetimeProgress(a, resolved).accumulatedDuration().equals(Duration.ofHours(1)), "stable resolution assigns once"); check(engine.periodSummary(a, resolved, interval("2026-01-01T10:30:00Z", "2026-01-01T11:00:00Z")).accumulatedDuration().equals(Duration.ofMinutes(30)), "period summary is clipped"); }
    private static void timerCompletionAtomicity() { RunningTimer timer = new RunningTimer("t1", "g1", t("2026-01-01T10:00:00Z")); InMemoryTimerStore success = new InMemoryTimerStore(timer, false); TimerCompletion completion = new TimerCommandService(new RecoveryEngine()).complete(timer, t("2026-01-01T10:30:00Z"), "r1", success); check(success.timer.isEmpty() && success.recovered.isPresent() && completion.recoveredTime().interval().duration().equals(Duration.ofMinutes(30)), "completion changes both values"); InMemoryTimerStore failure = new InMemoryTimerStore(timer, true); expectStateThrows(() -> new TimerCommandService(new RecoveryEngine()).complete(timer, t("2026-01-01T10:30:00Z"), "r2", failure)); check(failure.timer.isPresent() && failure.recovered.isEmpty(), "failed save preserves snapshot"); }
    private static void run(String name, Runnable test) { try { test.run(); passed++; System.out.println("PASS: " + name); } catch (RuntimeException | AssertionError failure) { System.err.println("FAIL: " + name + " - " + failure.getMessage()); throw failure; } }
    private static Instant t(String value) { return Instant.parse(value); }
    private static Interval interval(String start, String end) { return new Interval(t(start), t(end)); }
    private static void check(boolean condition, String message) { if (!condition) throw new AssertionError(message); }
    private static void expectThrows(Runnable action) { try { action.run(); throw new AssertionError("expected exception"); } catch (IllegalArgumentException expected) { } }
    private static void expectStateThrows(Runnable action) { try { action.run(); throw new AssertionError("expected state exception"); } catch (IllegalStateException expected) { } }
    private static final class InMemoryTimerStore implements TimerRecoveryStore { private Optional<RunningTimer> timer; private Optional<RecoveredTime> recovered = Optional.empty(); private final boolean fail; private InMemoryTimerStore(RunningTimer timer, boolean fail) { this.timer = Optional.of(timer); this.fail = fail; } public void completeAtomically(RunningTimer runningTimer, RecoveredTime value) { if (fail) throw new IllegalStateException("forced fake failure"); if (timer.isEmpty() || !timer.get().equals(runningTimer)) throw new IllegalStateException("timer changed"); recovered = Optional.of(value); timer = Optional.empty(); } }
}
